version: "3.7"
services:
  web1:
    build: ./quote_gen
    deploy:
      replicas: 2
    restart: always
    ports:
      - "5001-5002:5000"
    volumes:
      - ./quote_gen:/app
  
  web2:
    build: ./quote_disp
    deploy:
      replicas: 2
    restart: always
    ports:
      - "7001-7002:5001"
    depends_on:
      - web1
    volumes:
      - ./quote_disp:/app